server:
  port: 8084

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
