spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888

#server:
#  port: 8081
##  port: 0
#
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#      username: root
#      password: password
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 30000
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: top.oranges.*.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: deleteFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0