spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            group-id: sentinel
            rule-type: flow
            data-id: content-service-flow-rules
            data-type: json
        #          熔断降级配置文件
        degrade:
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            group-id: sentinel
            rule-type: degrade
            data-id: content-service-degrade-rules
            data-type: json

feign:
  sentinel:
    enabled: true

#server:
#  port: 9090
#
#spring:
#  application:
#    name: content-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#      username: root
#      password: password
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 30000
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: top.oranges.*.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: deleteFlag
#      logic-delete-value: 1
#      logic-not-delete-value: 0